var cake=new Vue({
	el:'#wrap',
	data:{
		city:'北京',
		weidao:[
			'全部口味',
			'乳脂奶油',
			'慕斯',
			'乳酪',
			'巧克力',
			'坚果',
			'水果',
			'咖啡',
			'冰淇淋',
			'应季',
		],
		weight:['445g','900g','1800g'],
		colorCurrentIndex:0,
		type:'全部口味',
		goods:{
			'乳脂奶油':[{goodsitem:'img/images/index/shengri/1.png',//单个商品图片
				goodsname:'曼生',//商品名字
				goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
				goodsprice:'198.00/450g',//商品价格
				},
				{goodsitem:'img/images/index/shengri/2.png',//单个商品图片
				goodsname:'蜜莉华',//商品名字
				goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
				goodsprice:'198.00/450g',//商品价格
				},
				{goodsitem:'img/images/index/shengri/3.png',//单个商品图片
				goodsname:'静子',//商品名字
				goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
				goodsprice:'198.00/450g',//商品价格
				},
				{goodsitem:'img/images/index/shengri/4.png',//单个商品图片
				goodsname:'茉莉花（精品）',//商品名字
				goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
				goodsprice:'198.00/450g',//商品价格
				},],
			'慕斯':[{goodsitem:'img/images/index/ertong/1.png',//单个商品图片
				goodsname:'慕斯',//商品名字
				goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
				goodsprice:'198.00/450g',//商品价格
				},
				{goodsitem:'img/images/index/ertong/2.png',//单个商品图片
				goodsname:'曼生',//商品名字
				goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
				goodsprice:'198.00/450g',//商品价格
				},
				{goodsitem:'img/images/index/ertong/3.png',//单个商品图片
				goodsname:'茉莉花',//商品名字
				goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
				goodsprice:'198.00/450g',//商品价格
				},
				{goodsitem:'img/images/index/ertong/4.png',//单个商品图片
				goodsname:'乳酪',//商品名字
				goodstype:'浆果裹慕斯蛋糕',//蛋糕类型
				goodsprice:'198.00/450g',//商品价格
				},],
			'乳酪':[{goodsitem:'img/images/index/juhui/1.png',//单个商品图片
					goodsname:'乳酪',//商品名字
					goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
					goodsprice:'198.00/450g',//商品价格
					},
					{goodsitem:'img/images/index/juhui/2.jpeg',//单个商品图片
					goodsname:'乳酪',//商品名字
					goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
					goodsprice:'198.00/450g',//商品价格
					},
					{goodsitem:'img/images/index/juhui/3.png',//单个商品图片
					goodsname:'茉莉花',//商品名字
					goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
					goodsprice:'198.00/450g',//商品价格
					},
					{goodsitem:'img/images/index/juhui/4.png',//单个商品图片
					goodsname:'金银',//商品名字
					goodstype:'浆果裹慕斯蛋糕',//蛋糕类型
					goodsprice:'198.00/450g',//商品价格
					},],
			'巧克力':[{goodsitem:'img/images/index/shengri/1.png',//单个商品图片
						goodsname:'琼可安利',//商品名字
						goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
						goodsprice:'198.00/450g',//商品价格
						},
						{goodsitem:'img/images/index/shengri/2.png',//单个商品图片
						goodsname:'黑声临',//商品名字
						goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
						goodsprice:'198.00/450g',//商品价格
						},
						{goodsitem:'img/images/index/shengri/3.png',//单个商品图片
						goodsname:'茉莉花',//商品名字
						goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
						goodsprice:'198.00/450g',//商品价格
						},
						{goodsitem:'img/images/index/shengri/4.png',//单个商品图片
						goodsname:'地底',//商品名字
						goodstype:'浆果裹慕斯蛋糕',//蛋糕类型
						goodsprice:'198.00/450g',//商品价格
						},],
			'坚果':[{goodsitem:'img/images/index/shengri/1.png',//单个商品图片
						goodsname:'琼可安利',//商品名字
						goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
						goodsprice:'198.00/450g',//商品价格
						},
						{goodsitem:'img/images/index/shengri/2.png',//单个商品图片
						goodsname:'黑声临',//商品名字
						goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
						goodsprice:'198.00/450g',//商品价格
						},
						{goodsitem:'img/images/index/shengri/3.png',//单个商品图片
						goodsname:'茉莉花',//商品名字
						goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
						goodsprice:'198.00/450g',//商品价格
						},
						{goodsitem:'img/images/index/shengri/4.png',//单个商品图片
						goodsname:'地底',//商品名字
						goodstype:'浆果裹慕斯蛋糕',//蛋糕类型
						goodsprice:'198.00/450g',//商品价格
						},],
		'水果':[{goodsitem:'img/images/index/shengri/1.png',//单个商品图片
							goodsname:'琼可安利',//商品名字
							goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
							goodsprice:'198.00/450g',//商品价格
							},
							{goodsitem:'img/images/index/shengri/2.png',//单个商品图片
							goodsname:'黑声临',//商品名字
							goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
							goodsprice:'198.00/450g',//商品价格
							},
							{goodsitem:'img/images/index/shengri/3.png',//单个商品图片
							goodsname:'茉莉花',//商品名字
							goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
							goodsprice:'198.00/450g',//商品价格
							},
							{goodsitem:'img/images/index/shengri/4.png',//单个商品图片
							goodsname:'地底',//商品名字
							goodstype:'浆果裹慕斯蛋糕',//蛋糕类型
							goodsprice:'198.00/450g',//商品价格
							},],
		'咖啡':[{goodsitem:'img/images/index/shengri/1.png',//单个商品图片
								goodsname:'琼可安利',//商品名字
								goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
								goodsprice:'198.00/450g',//商品价格
								},
								{goodsitem:'img/images/index/shengri/2.png',//单个商品图片
								goodsname:'黑声临',//商品名字
								goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
								goodsprice:'198.00/450g',//商品价格
								},
								{goodsitem:'img/images/index/shengri/3.png',//单个商品图片
								goodsname:'茉莉花',//商品名字
								goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
								goodsprice:'198.00/450g',//商品价格
								},
								{goodsitem:'img/images/index/shengri/4.png',//单个商品图片
								goodsname:'地底',//商品名字
								goodstype:'浆果裹慕斯蛋糕',//蛋糕类型
								goodsprice:'198.00/450g',//商品价格
								},],
			'咖啡':[{goodsitem:'img/images/index/shengri/1.png',//单个商品图片
				goodsname:'琼可安利',//商品名字
				goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
				goodsprice:'198.00/450g',//商品价格
				},
				{goodsitem:'img/images/index/shengri/2.png',//单个商品图片
				goodsname:'黑声临',//商品名字
				goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
				goodsprice:'198.00/450g',//商品价格
				},
				{goodsitem:'img/images/index/shengri/3.png',//单个商品图片
				goodsname:'茉莉花',//商品名字
				goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
				goodsprice:'198.00/450g',//商品价格
				},
				{goodsitem:'img/images/index/shengri/4.png',//单个商品图片
				goodsname:'地底',//商品名字
				goodstype:'浆果裹慕斯蛋糕',//蛋糕类型
				goodsprice:'198.00/450g',//商品价格
				},],
		'冰淇淋':[{goodsitem:'img/images/index/shengri/1.png',//单个商品图片
			goodsname:'琼可安利',//商品名字
			goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
			goodsprice:'198.00/450g',//商品价格
			},
			{goodsitem:'img/images/index/shengri/2.png',//单个商品图片
			goodsname:'黑声临',//商品名字
			goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
			goodsprice:'198.00/450g',//商品价格
			},
			{goodsitem:'img/images/index/shengri/3.png',//单个商品图片
			goodsname:'茉莉花',//商品名字
			goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
			goodsprice:'198.00/450g',//商品价格
			},
			{goodsitem:'img/images/index/shengri/4.png',//单个商品图片
			goodsname:'地底',//商品名字
			goodstype:'浆果裹慕斯蛋糕',//蛋糕类型
			goodsprice:'198.00/450g',//商品价格
			},],
		'应季':[{goodsitem:'img/images/index/shengri/1.png',//单个商品图片
			goodsname:'琼可安利',//商品名字
			goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
			goodsprice:'198.00/450g',//商品价格
			},
			{goodsitem:'img/images/index/shengri/2.png',//单个商品图片
			goodsname:'黑声临',//商品名字
			goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
			goodsprice:'198.00/450g',//商品价格
			},
			{goodsitem:'img/images/index/shengri/3.png',//单个商品图片
			goodsname:'茉莉花',//商品名字
			goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
			goodsprice:'198.00/450g',//商品价格
			},
			{goodsitem:'img/images/index/shengri/4.png',//单个商品图片
			goodsname:'地底',//商品名字
			goodstype:'浆果裹慕斯蛋糕',//蛋糕类型
			goodsprice:'198.00/450g',//商品价格
			},],	
		'全部口味':[{goodsitem:'img/images/index/shengri/1.png',//单个商品图片
			goodsname:'琼可安利',//商品名字
			goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
			goodsprice:'198.00/450g',//商品价格
			},
			{goodsitem:'img/images/index/shengri/2.png',//单个商品图片
			goodsname:'黑声临',//商品名字
			goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
			goodsprice:'198.00/450g',//商品价格
			},
			{goodsitem:'img/images/index/shengri/3.png',//单个商品图片
			goodsname:'茉莉花',//商品名字
			goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
			goodsprice:'198.00/450g',//商品价格
			},
			{goodsitem:'img/images/index/shengri/4.png',//单个商品图片
			goodsname:'地底',//商品名字
			goodstype:'浆果裹慕斯蛋糕',//蛋糕类型
			goodsprice:'198.00/450g',//商品价格
			},
			{goodsitem:'img/images/index/ertong/1.png',//单个商品图片
				goodsname:'琼可安利',//商品名字
				goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
				goodsprice:'198.00/450g',//商品价格
				},
				{goodsitem:'img/images/index/ertong/2.png',//单个商品图片
				goodsname:'黑声临',//商品名字
				goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
				goodsprice:'198.00/450g',//商品价格
				},
				{goodsitem:'img/images/index/ertong/3.png',//单个商品图片
				goodsname:'茉莉花',//商品名字
				goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
				goodsprice:'198.00/450g',//商品价格
				},
				{goodsitem:'img/images/index/ertong/4.png',//单个商品图片
				goodsname:'地底',//商品名字
				goodstype:'浆果裹慕斯蛋糕',//蛋糕类型
				goodsprice:'198.00/450g',//商品价格
				},
				{goodsitem:'img/images/index/juhui/1.png',//单个商品图片
					goodsname:'琼可安利',//商品名字
					goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
					goodsprice:'198.00/450g',//商品价格
					},
					{goodsitem:'img/images/index/juhui/2.jpeg',//单个商品图片
					goodsname:'黑声临',//商品名字
					goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
					goodsprice:'198.00/450g',//商品价格
					},
					{goodsitem:'img/images/index/juhui/3.png',//单个商品图片
					goodsname:'茉莉花',//商品名字
					goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
					goodsprice:'198.00/450g',//商品价格
					},
					{goodsitem:'img/images/index/juhui/4.png',//单个商品图片
					goodsname:'地底',//商品名字
					goodstype:'浆果裹慕斯蛋糕',//蛋糕类型
					goodsprice:'198.00/450g',//商品价格
					},
			],								
		},
			
	},
	methods:{
		changeColor(index){
			this.colorCurrentIndex=index,
			this.type=this.weidao[index]
		},
		
		
	}
})