new Vue({
	el:'#wrap',
	data:{
		city:'北京',
		imgUrl:[{url:'img/images/index/static/lunbo1/cebian1.jpg',
		name:'生日',
		a:'#shengri'
		},
		{url:'img/images/index/static/lunbo1/cebian2.jpg',
		name:'儿童',
		a:'#ertong'
		},
		{url:'img/images/index/static/lunbo1/cebian4.jpg',
		name:'新品',
		a:'#xinpin'
		},
		{url:'img/images/index/static/lunbo1/cebian3.jpg',
		name:'聚会',
		a:'#juhui'
		},
		],
		prefecture:[
			{
			ahref:'./shengri.html',
			hrefname:'shengri',
			name:'生日',//专区名字
			banner:'img/images/index/shengri/banner.jpg',//横幅
			goods:[
				{goodsitem:'img/images/index/shengri/1.png',//单个商品图片
				goodsname:'曼生',//商品名字
				goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
				goodsprice:'198.00/450g',//商品价格
				},
				{goodsitem:'img/images/index/shengri/2.png',//单个商品图片
				goodsname:'曼生',//商品名字
				goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
				goodsprice:'198.00/450g',//商品价格
				},
				{goodsitem:'img/images/index/shengri/3.png',//单个商品图片
				goodsname:'曼生',//商品名字
				goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
				goodsprice:'198.00/450g',//商品价格
				},
				{goodsitem:'img/images/index/shengri/4.png',//单个商品图片
				goodsname:'曼生',//商品名字
				goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
				goodsprice:'198.00/450g',//商品价格
				}
				]
			},
			{
				ahref:'./ertong.html',
			hrefname:'ertong',
			name:'儿童',//专区名字
			banner:'img/images/index/ertong/banner.jpg',//横幅
			goods:[
				{goodsitem:'img/images/index/shengri/1.png',//单个商品图片
				goodsname:'曼生',//商品名字
				goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
				goodsprice:'198.00/450g',//商品价格
				},
				{goodsitem:'img/images/index/shengri/2.png',//单个商品图片
				goodsname:'曼生',//商品名字
				goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
				goodsprice:'198.00/450g',//商品价格
				},
				{goodsitem:'img/images/index/shengri/3.png',//单个商品图片
				goodsname:'曼生',//商品名字
				goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
				goodsprice:'198.00/450g',//商品价格
				},
				{goodsitem:'img/images/index/shengri/4.png',//单个商品图片
				goodsname:'曼生',//商品名字
				goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
				goodsprice:'198.00/450g',//商品价格
				}
				]
			},
			{
			ahref:'./xinpin.html',
			hrefname:'xinpin',
			name:'新品',//专区名字
			banner:'img/images/index/xinpin/banner.jpg',//横幅
			goods:[
				{goodsitem:'img/images/index/xinpin/1.png',//单个商品图片
				goodsname:'茉莉花',//商品名字
				goodstype:'淡金色茉莉花',//蛋糕类型
				goodsprice:'198.00/450g',//商品价格
				},
				{goodsitem:'img/images/index/xinpin/2.png',//单个商品图片
				goodsname:'曼生',//商品名字
				goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
				goodsprice:'198.00/450g',//商品价格
				},
				{goodsitem:'img/images/index/xinpin/3.png',//单个商品图片
				goodsname:'豆酪',//商品名字
				goodstype:'专为儿童研发的豆腐芝士',//蛋糕类型
				goodsprice:'198.00/450g',//商品价格
				},
				{goodsitem:'img/images/index/shengri/4.png',//单个商品图片
				goodsname:'杰瑞',//商品名字
				goodstype:'芝士与坚果的完美融合',//蛋糕类型
				goodsprice:'198.00/450g',//商品价格
				}
				]
			},
			{
			ahref:'./juhui.html',
			hrefname:'juhui',
			name:'聚会',//专区名字
			banner:'img/images/index/juhui/banner.jpg',//横幅
			goods:[
				{goodsitem:'img/images/index/juhui/1.png',//单个商品图片
				goodsname:'曼生',//商品名字
				goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
				goodsprice:'198.00/450g',//商品价格
				},
				{goodsitem:'img/images/index/juhui/2.jpeg',//单个商品图片
				goodsname:'曼生',//商品名字
				goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
				goodsprice:'198.00/450g',//商品价格
				},
				{goodsitem:'img/images/index/juhui/3.png',//单个商品图片
				goodsname:'曼生',//商品名字
				goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
				goodsprice:'198.00/450g',//商品价格
				},
				{goodsitem:'img/images/index/juhui/4.png',//单个商品图片
				goodsname:'曼生',//商品名字
				goodstype:'树油奶油与浆果裹慕斯蛋糕',//蛋糕类型
				goodsprice:'198.00/450g',//商品价格
				}
				]
			},
			
		
			
		],
		
		// choose盒子
		chooseImg:[
			{name:'#shengri',
			imgUrl:'img/pic/click/shengri.jpg'
			},
			{name:'#ertong',
			imgUrl:'img/pic/click/ertong.jpg'
			},
			{name:'#xinpin',
			imgUrl:'img/pic/click/xinpin.jpg'
			},
			{name:'#juhui',
			imgUrl:'img/pic/click/juhui.jpg'
			}
		],
		
		//轮播图
		currentindex:0,
		timer:null,
		istran:true,
		isShow:false,
		weight:['450g','900g','1800g'],
		getindex:0,
		getitem:{},
		
	},

	methods:{	
		next(){
			this.currentindex++;
			this.istran=true; 
			if(this.currentindex>=this.imgUrl.length){
					this.currentindex=0;
					this.istran=false;
			};
			this.index=this.currentIndex
			if(this.currentIndex==this.imgUrl.length){
				this.index=0
			}
		},
		Settimer(){
			this.timer=setInterval(
			()=>{
				this.next()
			},2000)	
		},
		//展示隐藏价格
		show(index,item){
			this.getIndex(index,item)
		},
		showbereplace(item){
			this.getitem={}
		},
		//点击数量,点击的详细元素
		getIndex(index,item){
			this.getindex=index;
			this.getitem=item
		},
		getCity(){
			var url=location.search
			var codeurl= decodeURI(url)
			if(codeurl.indexOf("?")!=-1){
				var str=codeurl.substr(1);
				var strObj=str.split('=');
				this.city=strObj[1]
				
			}
			console.log(this.city)
		},
		// 更改地区
		changCity(){
			window.location.href=('./content.html?city='+this.city)
		},
		goNewGoods(ahref){
			window.location.href=ahref
		},
		goDetails(index){
			window.location.href=('details.html?key=lunbo')
		}
	},
	computed:{
		ulWidth(){
			 return 'transform:translateX(-'+this.currentindex*20+'%)'
		},
	},
	watch:{
	
	},
	created(){
		this.Settimer()
		this.getCity()
		
	},

	
	
})